server:
  port: 9001
  
spring:
  application:
    name: micservice-zuul-gateway
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
    
zuul:
  prefix: dhg
  ignored-services: "*"
  routes:
    mydept.serviceId: micservicecloud-dept
    mydept.path: /mydept/**    
    
info:
  app.name: dhg-micservicecloud
  company.name: www.dhg.com
  build.artifactid: $project.artifactid$
  build.version: 0.0.1-SNAPSHOT
    
  