server:
  port: 8003
  
mybatis:
 config-location: classpath:mybatis/mybatis.cfg.xml
 type-aliases-package: com.dhg.springCloud.entities
 mapper-locations:
  - classpath:mybatis/mapper/*.xml
 
spring:
  application:
    name: micservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudbd003
    username: root
    password: 123456
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-total: 5
      max-wait-millis: 200
  
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka #单机版的配置
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: micservicecloud-dept8003 #  服务主机名称的修改
    prefer-ip-address: true #访问路径可以显示ip地址
info:
  app.name: dhg-micservicecloud
  company.name: www.dhg.com
  build.artifactid: $project.artifactid$
  build.version: $project.version$
        
  